// Nomes em pt-BR das habilidades e traços de monstros (chave = nome em inglês do SRD, minúsculas, sem parênteses).
// Glossário próprio (não é a tradução oficial). Nomes de magias vêm de `SPELL_NAMES_PT`; sem entrada, fica em inglês.
export default {
  // magias fora do glossário do app
  geas: 'Missão',
  'dominate mind': 'Dominar Mente',
  'guiding light': 'Luz Guia',
  banish: 'Banimento',
  'acid spray': 'Jato de Ácido',
  scare: 'Amedrontar',
  "heroes' feast": 'Banquete dos Heróis',
  // ataques
  bite: 'Mordida',
  bites: 'Mordidas',
  claw: 'Garra',
  claws: 'Garras',
  'claw attack': 'Ataque de Garra',
  sting: 'Ferrão',
  stinger: 'Ferrão',
  'tail stinger': 'Ferrão da Cauda',
  tail: 'Cauda',
  'tail attack': 'Ataque de Cauda',
  'tail swipe': 'Rabada',
  'wing attack': 'Ataque de Asa',
  gore: 'Chifrada',
  hooves: 'Cascos',
  slam: 'Pancada',
  pseudopod: 'Pseudópode',
  pincer: 'Pinça',
  tentacle: 'Tentáculo',
  tentacles: 'Tentáculos',
  'tentacle slam': 'Pancada de Tentáculo',
  'tentacle attack or fling': 'Ataque de Tentáculo ou Arremesso',
  'paralyzing tentacles': 'Tentáculos Paralisantes',
  'charged tendril': 'Gavinha Carregada',
  tendril: 'Gavinha',
  talons: 'Garras (Talões)',
  tusk: 'Presa',
  tusks: 'Presas',
  ram: 'Aríete',
  rend: 'Dilacerar',
  'rotting fist': 'Punho Apodrecido',
  fist: 'Punho',
  'unarmed strike': 'Ataque Desarmado',
  crush: 'Esmagar',
  chomp: 'Mordiscada',
  gouge: 'Perfurar',
  pummel: 'Socar',
  lash: 'Chicotada',
  whip: 'Chicote',
  chain: 'Corrente',
  beard: 'Barba',
  spear: 'Lança',
  javelin: 'Dardo',
  handaxe: 'Machadinha',
  greataxe: 'Machado Grande',
  greatsword: 'Montante',
  longsword: 'Espada Longa',
  shortsword: 'Espada Curta',
  scimitar: 'Cimitarra',
  mace: 'Maça',
  maul: 'Malho',
  club: 'Clava',
  quarterstaff: 'Bordão',
  warhammer: 'Martelo de Guerra',
  battleaxe: 'Machado de Batalha',
  glaive: 'Glaive',
  longbow: 'Arco Longo',
  shortbow: 'Arco Curto',
  'hand crossbow': 'Besta de Mão',
  'light crossbow': 'Besta Leve',
  'heavy crossbow': 'Besta Pesada',
  'great bow': 'Arco Grande',
  'slaying longbow': 'Arco Longo Matador',
  'slaying bow': 'Arco Matador',
  'shield bash': 'Golpe de Escudo',
  'spiked bone club': 'Clava de Osso com Espinhos',
  'bone cudgel': 'Porrete de Osso',
  'tree club': 'Clava de Árvore',
  'vine staff': 'Cajado de Vinhas',
  'pact blade': 'Lâmina do Pacto',
  'burning hammer': 'Martelo Ardente',
  'flame whip': 'Chicote de Chamas',
  'lightning blade': 'Lâmina de Relâmpagos',
  'infernal glaive': 'Glaive Infernal',
  'infernal sting': 'Ferrão Infernal',
  'infernal tail': 'Cauda Infernal',
  'searing fork': 'Garfo Abrasador',
  'abyssal glaive': 'Glaive Abissal',
  'ocean spear': 'Lança Oceânica',
  'holy mace': 'Maça Sagrada',
  'holy burst': 'Explosão Sagrada',
  'storm blade': 'Lâmina da Tempestade',
  'storm sword': 'Espada da Tempestade',
  'thunderous mace': 'Maça Trovejante',
  'heated blade': 'Lâmina Aquecida',
  'flame sword': 'Espada Flamejante',
  'flame spear': 'Lança Flamejante',
  'fiery mace': 'Maça Ardente',
  'radiant sword': 'Espada Radiante',
  'frost axe': 'Machado Gélido',
  'ice spear': 'Lança de Gelo',
  'withering sword': 'Espada Murchadora',
  'necrotic sword': 'Espada Necrótica',
  'necrotic bow': 'Arco Necrótico',
  'necrotic strike': 'Golpe Necrótico',
  'umbral dagger': 'Adaga Umbral',
  'bladed arm': 'Braço de Lâminas',
  'poisoned dart': 'Dardo Envenenado',
  'enchanting bow': 'Arco Encantador',
  'hammer throw': 'Arremesso de Martelo',
  'boulder toss': 'Arremesso de Pedra',
  boulder: 'Pedra',
  rock: 'Pedra',
  'rock launch': 'Lançar Pedra',
  'trash lob': 'Arremesso de Lixo',
  'poisonous spittle': 'Cuspe Venenoso',
  'spit poison': 'Cuspir Veneno',
  'blinding spittle': 'Cuspe Cegante',
  'flying sword': 'Espada Voadora',
  'entangling rope': 'Corda Enredante',
  'rope of entanglement': 'Corda de Enredamento',
  'web strand': 'Fio de Teia',
  'web garrote': 'Garrote de Teia',
  'ice wall': 'Muralha de Gelo',
  // reações e movimento
  parry: 'Aparar',
  riposte: 'Contra-ataque',
  'redirect attack': 'Redirecionar Ataque',
  'deflect missile': 'Desviar Projétil',
  'rock catching': 'Pegar Pedra',
  'reflexive antennae': 'Antenas Reflexas',
  pursuit: 'Perseguição',
  protection: 'Proteção',
  'burst of ingenuity': 'Lampejo de Engenho',
  'unnerving gaze': 'Olhar Inquietante',
  'unnerving mask': 'Máscara Inquietante',
  'whirlwind of sand': 'Redemoinho de Areia',
  split: 'Dividir',
  'ink cloud': 'Nuvem de Tinta',
  shriek: 'Grito',
  'swarm of grasping hands': 'Enxame de Mãos Agarradoras',
  // movimento
  charge: 'Investida',
  'trampling charge': 'Investida Pisoteadora',
  pounce: 'Bote',
  leap: 'Salto',
  'deadly leap': 'Salto Mortal',
  flyby: 'Passagem Veloz',
  teleport: 'Teleporte',
  'deathly teleport': 'Teleporte Mortal',
  'radiant teleport': 'Teleporte Radiante',
  'invisible passage': 'Passagem Invisível',
  'ethereal stride': 'Passo Etéreo',
  'ethereal jaunt': 'Excursão Etérea',
  etherealness: 'Etereidade',
  'bubble dash': 'Disparada de Bolhas',
  swoop: 'Mergulho',
  'cloaked flight': 'Voo Encoberto',
  'arcane prowl': 'Espreita Arcana',
  prowl: 'Espreita',
  vanish: 'Desaparecer',
  'quick grapple': 'Agarrar Rápido',
  grab: 'Agarrar',
  attach: 'Fixar-se',
  reel: 'Puxar',
  fling: 'Arremessar',
  trample: 'Pisotear',
  rampage: 'Fúria Destrutiva',
  onslaught: 'Investida Furiosa',
  'create whirlwind': 'Criar Redemoinho',
  whirlwind: 'Redemoinho',
  vortex: 'Vórtice',
  // controle e sopros
  'fire breath': 'Sopro de Fogo',
  'cold breath': 'Sopro Gélido',
  'frost breath': 'Sopro de Gelo',
  'acid breath': 'Sopro Ácido',
  'poison breath': 'Sopro Venenoso',
  'lightning breath': 'Sopro de Relâmpago',
  'steam breath': 'Sopro de Vapor',
  'sleep breath': 'Sopro do Sono',
  'paralyzing breath': 'Sopro Paralisante',
  'repulsion breath': 'Sopro de Repulsão',
  'slowing breath': 'Sopro Lento',
  'weakening breath': 'Sopro Enfraquecedor',
  'blinding breath': 'Sopro Cegante',
  'petrifying breath': 'Sopro Petrificante',
  "dragon's breath": 'Sopro do Dragão',
  'breath weapons': 'Armas de Sopro',
  'frightful presence': 'Presença Aterradora',
  'horrifying visage': 'Semblante Horripilante',
  'horrific visage': 'Semblante Horrível',
  'unsettling visage': 'Semblante Perturbador',
  'horror nimbus': 'Auréola do Horror',
  'dreadful glare': 'Olhar Pavoroso',
  'death glare': 'Olhar Mortal',
  glare: 'Olhar',
  'blinding gaze': 'Olhar Cegante',
  'frightening gaze': 'Olhar Assustador',
  'petrifying gaze': 'Olhar Petrificante',
  'snake hair': 'Cabelos de Serpente',
  'stunning screech': 'Guincho Atordoante',
  'mind-rending roar': 'Rugido Dilacerante da Mente',
  roar: 'Rugido',
  'thunderous bellow': 'Berro Trovejante',
  'war cry': 'Grito de Guerra',
  'dread command': 'Comando Pavoroso',
  'baleful command': 'Comando Maligno',
  'blasphemous word': 'Palavra Blasfema',
  'commanding presence': 'Presença Dominante',
  leadership: 'Liderança',
  moan: 'Gemido',
  'luring song': 'Canção Sedutora',
  panpipes: 'Flauta de Pã',
  'fey charm': 'Encanto Feérico',
  charm: 'Encantar',
  "captain's charm": 'Charme do Capitão',
  'enthralling panache': 'Garbo Fascinante',
  mockery: 'Escárnio',
  'heart sight': 'Visão do Coração',
  'read thoughts': 'Ler Pensamentos',
  'mind invasion': 'Invasão Mental',
  'mind jolt': 'Choque Mental',
  'mind spike': 'Espinho Mental',
  'giggling magic': 'Magia Risonha',
  phantasms: 'Fantasmas',
  possession: 'Possessão',
  enslave: 'Escravizar',
  'nightmare haunting': 'Assombração de Pesadelo',
  'nightmare ray': 'Raio do Pesadelo',
  nightmare: 'Pesadelo',
  'children of the night': 'Filhos da Noite',
  // veneno, ácido, dreno
  'death burst': 'Explosão de Morte',
  'death throes': 'Convulsões da Morte',
  'life drain': 'Dreno de Vida',
  'psychic drain': 'Dreno Psíquico',
  'draining kiss': 'Beijo Drenador',
  'disrupt life': 'Perturbar a Vida',
  'consume life': 'Consumir Vida',
  'consume memories': 'Consumir Memórias',
  'corrupting touch': 'Toque Corruptor',
  'cursed touch': 'Toque Amaldiçoado',
  'paralyzing touch': 'Toque Paralisante',
  'intoxicating touch': 'Toque Inebriante',
  'healing touch': 'Toque Curativo',
  'heal self': 'Curar a Si Mesmo',
  'petrifying bite': 'Mordida Petrificante',
  'grave strike': 'Golpe Sepulcral',
  'deathless strike': 'Golpe Imortal',
  'deathless agility': 'Agilidade Imortal',
  ink: 'Tinta',
  'toxic ink': 'Tinta Tóxica',
  'fetid cloud': 'Nuvem Fétida',
  'noxious miasma': 'Miasma Nocivo',
  'cloud of insects': 'Nuvem de Insetos',
  spores: 'Esporos',
  smother: 'Sufocar',
  engulf: 'Envolver',
  whelm: 'Engolfar',
  swallow: 'Engolir',
  'cast a spell': 'Lançar Magia',
  cantrip: 'Truque',
  'blinding dust': 'Poeira Cegante',
  'scorching sands': 'Areias Escaldantes',
  'searing burst': 'Rajada Abrasadora',
  'fiery rays': 'Raios Flamejantes',
  'cold gale': 'Vendaval Gélido',
  'freezing burst': 'Rajada Congelante',
  chill: 'Calafrio',
  'sonic boom': 'Estrondo Sônico',
  thunderclap: 'Trovoada',
  thundercloud: 'Nuvem de Trovão',
  cacophony: 'Cacofonia',
  'lightning storm': 'Tempestade de Raios',
  'lightning strike': 'Descarga de Relâmpago',
  'storm bolt': 'Raio da Tempestade',
  'vitriolic sphere': 'Esfera Vitriólica',
  'blazing light': 'Luz Ofuscante',
  noxious: 'Nocivo',
  'ignited illumination': 'Iluminação Incandescente',
  'darkness aura': 'Aura de Escuridão',
  'heated body': 'Corpo Aquecido',
  'shadow stealth': 'Furtividade Sombria',
  'destroy metal': 'Destruir Metal',
  antennae: 'Antenas',
  'aquatic charge': 'Investida Aquática',
  'divine aid': 'Auxílio Divino',
  'create specter': 'Criar Espectro',
  'create undead': 'Criar Mortos-vivos',
  'summon demon': 'Convocar Demônio',
  'summon mephits': 'Convocar Mefits',
  'animate trees': 'Animar Árvores',
  'tree stride': 'Caminhar por Árvores',
  'shimmering shield': 'Escudo Cintilante',
  'weight of years': 'Peso dos Anos',
  'world-shaking movement': 'Movimento Abalador do Mundo',
  'charging horn': 'Chifre Investidor',
  "unicorn's blessing": 'Bênção do Unicórnio',
  'conjure infernal chain': 'Conjurar Corrente Infernal',
  'hellfire spellcasting': 'Conjuração do Fogo Infernal',
  'magic of the spider queen': 'Magia da Rainha Aranha',
  'protective magic': 'Magia Protetora',
  'channel negative energy': 'Canalizar Energia Negativa',
  horrific: 'Horrível',
  hasten: 'Apressar',
  elementalism: 'Elementalismo',
  beguile: 'Seduzir',
  'dancing lights': 'Luzes Dançantes',
  detect: 'Detectar',
  move: 'Mover',
  attack: 'Atacar',
  'illusory appearance': 'Aparência Ilusória',
  'shape-shift': 'Mudar de Forma',
  shapechange: 'Mudar de Forma',
  'change shape': 'Mudar de Forma',
  consume: 'Consumir',
  shred: 'Retalhar',
  // traços
  'magic resistance': 'Resistência à Magia',
  'greater magic resistance': 'Resistência Maior à Magia',
  'legendary resistance': 'Resistência Lendária',
  'pack tactics': 'Táticas de Matilha',
  'blood frenzy': 'Frenesi Sanguinário',
  'martial advantage': 'Vantagem Marcial',
  'undead fortitude': 'Fortitude de Morto-vivo',
  relentless: 'Implacável',
  regeneration: 'Regeneração',
  constrict: 'Constringir',
  'tail attack ': 'Ataque de Cauda',
  fly: 'Voar',
  invisibility: 'Invisibilidade',
  light: 'Luz',
  'dispel magic': 'Dissipar Magia',
  'dispel evil and good': 'Dissipar o Bem e o Mal',
};
