/**
 * Glossário próprio de nomes em pt-BR para o Bestiário e o Compêndio de Magias (F11-6).
 *
 * Não é a tradução oficial da Wizards of the Coast (que tem direitos autorais próprios,
 * separados da licença CC-BY do texto em inglês do SRD): é uma tradução direta, nossa,
 * de nomes descritivos — o mesmo tipo de trabalho que qualquer tradutor faria a partir do
 * termo em inglês. Nomes sem entrada aqui caem no original em inglês (ver `monsterNamePt`
 * e `spellNamePt`), o que é esperado para termos mais raros do SRD 2024.
 */

export const MONSTER_NAMES_PT: Readonly<Record<string, string>> = {
  Aboleth: 'Aboleth',
  Acolyte: 'Acólito',
  'Adult Black Dragon': 'Dragão Negro Adulto',
  'Adult Blue Dragon': 'Dragão Azul Adulto',
  'Adult Brass Dragon': 'Dragão de Latão Adulto',
  'Adult Bronze Dragon': 'Dragão de Bronze Adulto',
  'Adult Copper Dragon': 'Dragão de Cobre Adulto',
  'Adult Gold Dragon': 'Dragão Dourado Adulto',
  'Adult Green Dragon': 'Dragão Verde Adulto',
  'Adult Red Dragon': 'Dragão Vermelho Adulto',
  'Adult Silver Dragon': 'Dragão Prateado Adulto',
  'Adult White Dragon': 'Dragão Branco Adulto',
  'Air Elemental': 'Elemental do Ar',
  Allosaurus: 'Alossauro',
  'Ancient Black Dragon': 'Dragão Negro Ancião',
  'Ancient Blue Dragon': 'Dragão Azul Ancião',
  'Ancient Brass Dragon': 'Dragão de Latão Ancião',
  'Ancient Bronze Dragon': 'Dragão de Bronze Ancião',
  'Ancient Copper Dragon': 'Dragão de Cobre Ancião',
  'Ancient Gold Dragon': 'Dragão Dourado Ancião',
  'Ancient Green Dragon': 'Dragão Verde Ancião',
  'Ancient Red Dragon': 'Dragão Vermelho Ancião',
  'Ancient Silver Dragon': 'Dragão Prateado Ancião',
  'Ancient White Dragon': 'Dragão Branco Ancião',
  Androsphinx: 'Androesfinge',
  'Animated Armor': 'Armadura Animada',
  'Animated Flying Sword': 'Espada Voadora Animada',
  'Animated Rug of Smothering': 'Tapete Sufocante Animado',
  Ankheg: 'Ankheg',
  Ankylosaurus: 'Anquilossauro',
  Ape: 'Macaco',
  Archelon: 'Archelon',
  Archmage: 'Arquimago',
  Assassin: 'Assassino',
  'Awakened Shrub': 'Arbusto Desperto',
  'Awakened Tree': 'Árvore Desperta',
  'Axe Beak': 'Bico-de-Machado',
  Azer: 'Azer',
  'Azer Sentinel': 'Azer Sentinela',
  Baboon: 'Babuíno',
  Badger: 'Texugo',
  Balor: 'Balor',
  Bandit: 'Bandido',
  'Bandit Captain': 'Capitão Bandido',
  'Barbed Devil': 'Diabo Farpado',
  Basilisk: 'Basilisco',
  Bat: 'Morcego',
  'Bearded Devil': 'Diabo Barbudo',
  Behir: 'Behir',
  Berserker: 'Berserker',
  'Black Bear': 'Urso Negro',
  'Black Dragon Wyrmling': 'Filhote de Dragão Negro',
  'Black Pudding': 'Pudim Negro',
  'Blink Dog': 'Cão Piscante',
  'Blood Hawk': 'Falcão-sanguinário',
  'Blue Dragon Wyrmling': 'Filhote de Dragão Azul',
  Boar: 'Javali',
  'Bone Devil': 'Diabo Ósseo',
  'Brass Dragon Wyrmling': 'Filhote de Dragão de Latão',
  'Bronze Dragon Wyrmling': 'Filhote de Dragão de Bronze',
  'Brown Bear': 'Urso Pardo',
  Bugbear: 'Bugbear',
  'Bugbear Stalker': 'Bugbear Perseguidor',
  'Bugbear Warrior': 'Bugbear Guerreiro',
  Bulette: 'Bulette',
  Camel: 'Camelo',
  Cat: 'Gato',
  Centaur: 'Centauro',
  'Centaur Trooper': 'Centauro Soldado',
  'Chain Devil': 'Diabo das Correntes',
  Chimera: 'Quimera',
  Chuul: 'Chuul',
  'Clay Golem': 'Golem de Argila',
  Cloaker: 'Cloaker',
  'Cloud Giant': 'Gigante das Nuvens',
  Cockatrice: 'Cocatriz',
  Commoner: 'Plebeu',
  'Constrictor Snake': 'Serpente Constritora',
  'Copper Dragon Wyrmling': 'Filhote de Dragão de Cobre',
  Couatl: 'Couatl',
  Crab: 'Caranguejo',
  Crocodile: 'Crocodilo',
  'Cult Fanatic': 'Fanático do Culto',
  Cultist: 'Cultista',
  'Cultist Fanatic': 'Cultista Fanático',
  Darkmantle: 'Manto Sombrio',
  'Death Dog': 'Cão da Morte',
  'Deep Gnome (Svirfneblin)': 'Gnomo das Profundezas (Svirfneblin)',
  Deer: 'Cervo',
  Deva: 'Deva',
  'Dire Wolf': 'Lobo Terrível',
  Djinni: 'Djinni',
  Doppelganger: 'Doppelganger',
  'Draft Horse': 'Cavalo de Tiro',
  'Dragon Turtle': 'Tartaruga-dragão',
  Dretch: 'Dretch',
  Drider: 'Drider',
  Drow: 'Drow',
  Druid: 'Druida',
  Dryad: 'Dríade',
  Duergar: 'Duergar',
  'Dust Mephit': 'Mefita da Poeira',
  Eagle: 'Águia',
  'Earth Elemental': 'Elemental da Terra',
  Efreeti: 'Efreeti',
  Elephant: 'Elefante',
  Elk: 'Alce',
  Erinyes: 'Erínias',
  Ettercap: 'Ettercap',
  Ettin: 'Ettin',
  'Fire Elemental': 'Elemental do Fogo',
  'Fire Giant': 'Gigante do Fogo',
  'Flesh Golem': 'Golem de Carne',
  'Flying Snake': 'Serpente Voadora',
  'Flying Sword': 'Espada Voadora',
  Frog: 'Sapo',
  'Frost Giant': 'Gigante da Geada',
  Gargoyle: 'Gárgula',
  'Gelatinous Cube': 'Cubo Gelatinoso',
  Ghast: 'Carniçal Voraz',
  Ghost: 'Fantasma',
  Ghoul: 'Carniçal',
  'Giant Ape': 'Macaco Gigante',
  'Giant Badger': 'Texugo Gigante',
  'Giant Bat': 'Morcego Gigante',
  'Giant Boar': 'Javali Gigante',
  'Giant Centipede': 'Centopeia Gigante',
  'Giant Constrictor Snake': 'Serpente Constritora Gigante',
  'Giant Crab': 'Caranguejo Gigante',
  'Giant Crocodile': 'Crocodilo Gigante',
  'Giant Eagle': 'Águia Gigante',
  'Giant Elk': 'Alce Gigante',
  'Giant Fire Beetle': 'Besouro-de-fogo Gigante',
  'Giant Fly': 'Mosca Gigante',
  'Giant Frog': 'Sapo Gigante',
  'Giant Goat': 'Cabra Gigante',
  'Giant Hyena': 'Hiena Gigante',
  'Giant Lizard': 'Lagarto Gigante',
  'Giant Octopus': 'Polvo Gigante',
  'Giant Owl': 'Coruja Gigante',
  'Giant Poisonous Snake': 'Serpente Venenosa Gigante',
  'Giant Rat': 'Rato Gigante',
  'Giant Rat (Diseased)': 'Rato Gigante (Doente)',
  'Giant Scorpion': 'Escorpião Gigante',
  'Giant Sea Horse': 'Cavalo-marinho Gigante',
  'Giant Seahorse': 'Cavalo-marinho Gigante',
  'Giant Shark': 'Tubarão Gigante',
  'Giant Spider': 'Aranha Gigante',
  'Giant Toad': 'Sapo-cururu Gigante',
  'Giant Venomous Snake': 'Serpente Venenosa Gigante',
  'Giant Vulture': 'Urubu Gigante',
  'Giant Wasp': 'Vespa Gigante',
  'Giant Weasel': 'Doninha Gigante',
  'Giant Wolf Spider': 'Aranha-lobo Gigante',
  'Gibbering Mouther': 'Boca Tagarela',
  Glabrezu: 'Glabrezu',
  Gladiator: 'Gladiador',
  Gnoll: 'Gnoll',
  'Gnoll Warrior': 'Gnoll Guerreiro',
  Goat: 'Cabra',
  Goblin: 'Goblin',
  'Goblin Boss': 'Chefe Goblin',
  'Goblin Minion': 'Lacaio Goblin',
  'Goblin Warrior': 'Goblin Guerreiro',
  'Gold Dragon Wyrmling': 'Filhote de Dragão Dourado',
  Gorgon: 'Górgone',
  'Gray Ooze': 'Limo Cinzento',
  'Green Dragon Wyrmling': 'Filhote de Dragão Verde',
  'Green Hag': 'Bruxa Verde',
  Grick: 'Grick',
  Griffon: 'Grifo',
  Grimlock: 'Grimlock',
  Guard: 'Guarda',
  'Guard Captain': 'Capitão da Guarda',
  'Guardian Naga': 'Naga Guardiã',
  Gynosphinx: 'Ginoesfinge',
  'Half-Dragon': 'Meio-Dragão',
  'Half-Red Dragon Veteran': 'Veterano Meio-Dragão Vermelho',
  Harpy: 'Harpia',
  Hawk: 'Falcão',
  'Hell Hound': 'Cão do Inferno',
  Hezrou: 'Hezrou',
  'Hill Giant': 'Gigante das Colinas',
  Hippogriff: 'Hipogrifo',
  Hippopotamus: 'Hipopótamo',
  Hobgoblin: 'Hobgoblin',
  'Hobgoblin Captain': 'Capitão Hobgoblin',
  'Hobgoblin Warrior': 'Hobgoblin Guerreiro',
  Homunculus: 'Homúnculo',
  'Horned Devil': 'Diabo Cornudo',
  'Hunter Shark': 'Tubarão Caçador',
  Hydra: 'Hidra',
  Hyena: 'Hiena',
  'Ice Devil': 'Diabo do Gelo',
  'Ice Mephit': 'Mefita do Gelo',
  Imp: 'Diabrete',
  Incubus: 'Íncubo',
  'Invisible Stalker': 'Perseguidor Invisível',
  'Iron Golem': 'Golem de Ferro',
  Jackal: 'Chacal',
  'Killer Whale': 'Orca',
  Knight: 'Cavaleiro',
  Kobold: 'Kobold',
  'Kobold Warrior': 'Kobold Guerreiro',
  Kraken: 'Kraken',
  Lamia: 'Lâmia',
  Lemure: 'Lêmure',
  Lich: 'Lich',
  Lion: 'Leão',
  Lizard: 'Lagarto',
  Lizardfolk: 'Homem-lagarto',
  Mage: 'Mago',
  'Magma Mephit': 'Mefita do Magma',
  Magmin: 'Magmin',
  Mammoth: 'Mamute',
  Manticore: 'Mantícora',
  Marilith: 'Marilith',
  Mastiff: 'Mastim',
  Medusa: 'Medusa',
  Merfolk: 'Tritão',
  'Merfolk Skirmisher': 'Tritão Batedor',
  Merrow: 'Merrow',
  Mimic: 'Mímico',
  Minotaur: 'Minotauro',
  'Minotaur Skeleton': 'Esqueleto de Minotauro',
  'Minotaur of Baphomet': 'Minotauro de Baphomet',
  Mule: 'Mula',
  Mummy: 'Múmia',
  'Mummy Lord': 'Senhor Múmia',
  Nalfeshnee: 'Nalfeshnee',
  'Night Hag': 'Bruxa da Noite',
  Nightmare: 'Pesadelo',
  Noble: 'Nobre',
  'Ochre Jelly': 'Geleia Ocre',
  Octopus: 'Polvo',
  Ogre: 'Ogro',
  'Ogre Zombie': 'Zumbi Ogro',
  Oni: 'Oni',
  Orc: 'Orc',
  Otyugh: 'Otyugh',
  Owl: 'Coruja',
  Owlbear: 'Urso-coruja',
  Panther: 'Pantera',
  Pegasus: 'Pégaso',
  'Phase Spider': 'Aranha das Fases',
  Piranha: 'Piranha',
  Pirate: 'Pirata',
  'Pirate Captain': 'Capitão Pirata',
  'Pit Fiend': 'Diabo do Fosso',
  Planetar: 'Planetar',
  Plesiosaurus: 'Plesiossauro',
  'Poisonous Snake': 'Serpente Venenosa',
  'Polar Bear': 'Urso Polar',
  Pony: 'Pônei',
  Priest: 'Sacerdote',
  'Priest Acolyte': 'Sacerdote Acólito',
  Pseudodragon: 'Pseudodragão',
  Pteranodon: 'Pteranodonte',
  'Purple Worm': 'Verme Púrpura',
  Quasit: 'Quasit',
  Quipper: 'Quipper',
  Rakshasa: 'Rakshasa',
  Rat: 'Rato',
  Raven: 'Corvo',
  'Red Dragon Wyrmling': 'Filhote de Dragão Vermelho',
  'Reef Shark': 'Tubarão de Recife',
  Remorhaz: 'Remorhaz',
  Rhinoceros: 'Rinoceronte',
  'Riding Horse': 'Cavalo de Montaria',
  Roc: 'Roca',
  Roper: 'Roper',
  'Rug of Smothering': 'Tapete Sufocante',
  'Rust Monster': 'Monstro da Ferrugem',
  'Saber-Toothed Tiger': 'Tigre-dente-de-sabre',
  Sahuagin: 'Sahuagin',
  'Sahuagin Warrior': 'Sahuagin Guerreiro',
  Salamander: 'Salamandra',
  Satyr: 'Sátiro',
  Scorpion: 'Escorpião',
  Scout: 'Batedor',
  'Sea Hag': 'Bruxa do Mar',
  'Sea Horse': 'Cavalo-marinho',
  Seahorse: 'Cavalo-marinho',
  Shadow: 'Sombra',
  'Shambling Mound': 'Monte Cambaleante',
  'Shield Guardian': 'Guardião de Escudo',
  Shrieker: 'Cogumelo Gritador',
  'Shrieker Fungus': 'Fungo Gritador',
  'Silver Dragon Wyrmling': 'Filhote de Dragão Prateado',
  Skeleton: 'Esqueleto',
  Solar: 'Solar',
  Specter: 'Espectro',
  'Sphinx of Lore': 'Esfinge do Saber',
  'Sphinx of Valor': 'Esfinge do Valor',
  'Sphinx of Wonder': 'Esfinge do Assombro',
  Spider: 'Aranha',
  'Spirit Naga': 'Naga Espiritual',
  Sprite: 'Sprite',
  Spy: 'Espião',
  'Steam Mephit': 'Mefita do Vapor',
  Stirge: 'Stirge',
  'Stone Giant': 'Gigante de Pedra',
  'Stone Golem': 'Golem de Pedra',
  'Storm Giant': 'Gigante da Tempestade',
  Succubus: 'Súcubo',
  'Succubus/Incubus': 'Súcubo/Íncubo',
  'Swarm of Bats': 'Enxame de Morcegos',
  'Swarm of Beetles': 'Enxame de Besouros',
  'Swarm of Centipedes': 'Enxame de Centopeias',
  'Swarm of Crawling Claws': 'Enxame de Garras Rastejantes',
  'Swarm of Insects': 'Enxame de Insetos',
  'Swarm of Piranhas': 'Enxame de Piranhas',
  'Swarm of Poisonous Snakes': 'Enxame de Serpentes Venenosas',
  'Swarm of Quippers': 'Enxame de Quippers',
  'Swarm of Rats': 'Enxame de Ratos',
  'Swarm of Ravens': 'Enxame de Corvos',
  'Swarm of Spiders': 'Enxame de Aranhas',
  'Swarm of Venomous Snakes': 'Enxame de Serpentes Venenosas',
  'Swarm of Wasps': 'Enxame de Vespas',
  Tarrasque: 'Tarrasca',
  Thug: 'Capanga',
  Tiger: 'Tigre',
  Tough: 'Valentão',
  'Tough Boss': 'Valentão Chefe',
  Treant: 'Treant',
  'Tribal Warrior': 'Guerreiro Tribal',
  Triceratops: 'Tricerátops',
  Troll: 'Troll',
  'Troll Limb': 'Membro de Troll',
  'Tyrannosaurus Rex': 'Tiranossauro Rex',
  Unicorn: 'Unicórnio',
  Vampire: 'Vampiro',
  'Vampire Familiar': 'Familiar Vampírico',
  'Vampire Spawn': 'Descendente de Vampiro',
  'Venomous Snake': 'Serpente Venenosa',
  Veteran: 'Veterano',
  'Violet Fungus': 'Fungo Violeta',
  Vrock: 'Vrock',
  Vulture: 'Urubu',
  Warhorse: 'Cavalo de Guerra',
  'Warhorse Skeleton': 'Esqueleto de Cavalo de Guerra',
  'Warrior Infantry': 'Guerreiro de Infantaria',
  'Warrior Veteran': 'Guerreiro Veterano',
  'Water Elemental': 'Elemental da Água',
  Weasel: 'Doninha',
  Werebear: 'Homem-urso',
  Wereboar: 'Homem-javali',
  Wererat: 'Homem-rato',
  Weretiger: 'Homem-tigre',
  Werewolf: 'Lobisomem',
  'White Dragon Wyrmling': 'Filhote de Dragão Branco',
  Wight: 'Wight',
  "Will-o'-Wisp": 'Fogo-fátuo',
  'Winter Wolf': 'Lobo do Inverno',
  Wolf: 'Lobo',
  Worg: 'Worg',
  Wraith: 'Vulto',
  Wyvern: 'Wyvern',
  Xorn: 'Xorn',
  'Young Black Dragon': 'Dragão Negro Jovem',
  'Young Blue Dragon': 'Dragão Azul Jovem',
  'Young Brass Dragon': 'Dragão de Latão Jovem',
  'Young Bronze Dragon': 'Dragão de Bronze Jovem',
  'Young Copper Dragon': 'Dragão de Cobre Jovem',
  'Young Gold Dragon': 'Dragão Dourado Jovem',
  'Young Green Dragon': 'Dragão Verde Jovem',
  'Young Red Dragon': 'Dragão Vermelho Jovem',
  'Young Silver Dragon': 'Dragão Prateado Jovem',
  'Young White Dragon': 'Dragão Branco Jovem',
  Zombie: 'Zumbi',
};

export const SPELL_NAMES_PT: Readonly<Record<string, string>> = {
  'Acid Arrow': 'Flecha Ácida',
  'Acid Splash': 'Respingo Ácido',
  Aid: 'Auxílio',
  Alarm: 'Alarme',
  'Alter Self': 'Alterar-se',
  'Animal Friendship': 'Amizade com Animais',
  'Animal Messenger': 'Mensageiro Animal',
  'Animal Shapes': 'Formas Animais',
  'Animate Dead': 'Animar Mortos',
  'Animate Objects': 'Animar Objetos',
  'Antilife Shell': 'Concha Antivida',
  'Antimagic Field': 'Campo Antimagia',
  'Antipathy/Sympathy': 'Antipatia/Simpatia',
  'Arcane Eye': 'Olho Arcano',
  'Arcane Hand': 'Mão Arcana',
  'Arcane Lock': 'Tranca Arcana',
  'Arcane Sword': 'Espada Arcana',
  "Arcanist's Magic Aura": 'Aura Mágica do Arcanista',
  'Astral Projection': 'Projeção Astral',
  Augury: 'Augúrio',
  'Aura of Life': 'Aura de Vida',
  Awaken: 'Despertar',
  Bane: 'Perdição',
  Banishment: 'Banimento',
  Barkskin: 'Pele de Casca',
  'Beacon of Hope': 'Farol de Esperança',
  Befuddlement: 'Confusão Mental',
  'Bestow Curse': 'Lançar Maldição',
  'Black Tentacles': 'Tentáculos Negros',
  'Blade Barrier': 'Barreira de Lâminas',
  Bless: 'Bênção',
  Blight: 'Praga',
  'Blindness/Deafness': 'Cegueira/Surdez',
  Blink: 'Piscar',
  Blur: 'Borrão',
  'Branding Smite': 'Golpe de Marca',
  'Burning Hands': 'Mãos Flamejantes',
  'Call Lightning': 'Chamar Relâmpago',
  'Calm Emotions': 'Acalmar Emoções',
  'Chain Lightning': 'Corrente de Relâmpagos',
  'Charm Monster': 'Encantar Monstro',
  'Charm Person': 'Encantar Pessoa',
  'Chill Touch': 'Toque Gélido',
  'Chromatic Orb': 'Orbe Cromático',
  'Circle of Death': 'Círculo da Morte',
  Clairvoyance: 'Clarividência',
  Clone: 'Clone',
  Cloudkill: 'Nuvem Mortífera',
  'Color Spray': 'Explosão de Cores',
  Command: 'Comando',
  Commune: 'Comunhão',
  'Commune with Nature': 'Comunhão com a Natureza',
  'Comprehend Languages': 'Compreender Idiomas',
  Compulsion: 'Compulsão',
  'Cone of Cold': 'Cone de Frio',
  Confusion: 'Confusão',
  'Conjure Animals': 'Conjurar Animais',
  'Conjure Celestial': 'Conjurar Celestial',
  'Conjure Elemental': 'Conjurar Elemental',
  'Conjure Fey': 'Conjurar Feérico',
  'Conjure Minor Elementals': 'Conjurar Elementais Menores',
  'Conjure Woodland Beings': 'Conjurar Seres da Floresta',
  'Contact Other Plane': 'Contatar Outro Plano',
  Contagion: 'Contágio',
  Contingency: 'Contingência',
  'Continual Flame': 'Chama Contínua',
  'Control Water': 'Controlar Água',
  'Control Weather': 'Controlar o Clima',
  Counterspell: 'Contramágica',
  'Create Food and Water': 'Criar Comida e Água',
  'Create Undead': 'Criar Morto-vivo',
  'Create or Destroy Water': 'Criar ou Destruir Água',
  Creation: 'Criação',
  'Cure Wounds': 'Curar Ferimentos',
  'Dancing Lights': 'Luzes Dançantes',
  Darkness: 'Trevas',
  Darkvision: 'Visão no Escuro',
  Daylight: 'Luz do Dia',
  'Death Ward': 'Proteção contra a Morte',
  'Delayed Blast Fireball': 'Bola de Fogo de Explosão Retardada',
  Demiplane: 'Semiplano',
  'Detect Evil and Good': 'Detectar o Mal e o Bem',
  'Detect Magic': 'Detectar Magia',
  'Detect Poison and Disease': 'Detectar Veneno e Doença',
  'Detect Thoughts': 'Detectar Pensamentos',
  'Dimension Door': 'Porta Dimensional',
  'Disguise Self': 'Disfarçar-se',
  Disintegrate: 'Desintegrar',
  'Dispel Evil and Good': 'Dissipar o Mal e o Bem',
  'Dispel Magic': 'Dissipar Magia',
  'Dissonant Whispers': 'Sussurros Dissonantes',
  Divination: 'Adivinhação',
  'Divine Favor': 'Favor Divino',
  'Divine Smite': 'Punição Divina',
  'Divine Word': 'Palavra Divina',
  'Dominate Beast': 'Dominar Besta',
  'Dominate Monster': 'Dominar Monstro',
  'Dominate Person': 'Dominar Pessoa',
  "Dragon's Breath": 'Sopro de Dragão',
  Dream: 'Sonho',
  Druidcraft: 'Ofício Druídico',
  Earthquake: 'Terremoto',
  'Eldritch Blast': 'Explosão Sobrenatural',
  Elementalism: 'Elementalismo',
  'Enhance Ability': 'Melhorar Habilidade',
  'Enlarge/Reduce': 'Aumentar/Reduzir',
  'Ensnaring Strike': 'Golpe Enlaçador',
  Entangle: 'Emaranhar',
  Enthrall: 'Cativar',
  Etherealness: 'Estado Etéreo',
  'Expeditious Retreat': 'Retirada Expedita',
  Eyebite: 'Mordida do Olhar',
  Fabricate: 'Fabricar',
  'Faerie Fire': 'Fogo Feérico',
  'Faithful Hound': 'Cão Fiel',
  'False Life': 'Vida Falsa',
  Fear: 'Medo',
  'Feather Fall': 'Queda de Pena',
  Feeblemind: 'Enfraquecer a Mente',
  'Find Familiar': 'Encontrar Familiar',
  'Find Steed': 'Encontrar Montaria',
  'Find Traps': 'Encontrar Armadilhas',
  'Find the Path': 'Encontrar o Caminho',
  'Finger of Death': 'Dedo da Morte',
  'Fire Bolt': 'Raio de Fogo',
  'Fire Shield': 'Escudo de Fogo',
  'Fire Storm': 'Tempestade de Fogo',
  Fireball: 'Bola de Fogo',
  'Flame Blade': 'Lâmina de Chamas',
  'Flame Strike': 'Golpe de Chamas',
  'Flaming Sphere': 'Esfera Flamejante',
  'Flesh to Stone': 'Carne em Pedra',
  'Floating Disk': 'Disco Flutuante',
  Fly: 'Voar',
  'Fog Cloud': 'Nuvem de Neblina',
  Forbiddance: 'Interdição',
  Forcecage: 'Gaiola de Força',
  Foresight: 'Presciência',
  'Freedom of Movement': 'Liberdade de Movimento',
  'Freezing Sphere': 'Esfera Congelante',
  'Gaseous Form': 'Forma Gasosa',
  Gate: 'Portal',
  Geas: 'Geas',
  'Gentle Repose': 'Repouso Sereno',
  'Giant Insect': 'Inseto Gigante',
  Glibness: 'Lábia',
  'Globe of Invulnerability': 'Globo de Invulnerabilidade',
  'Glyph of Warding': 'Glifo de Proteção',
  Goodberry: 'Baga Nutritiva',
  Grease: 'Graxa',
  'Greater Invisibility': 'Invisibilidade Maior',
  'Greater Restoration': 'Restauração Maior',
  'Guardian of Faith': 'Guardião da Fé',
  'Guards and Wards': 'Guardas e Vigias',
  Guidance: 'Orientação',
  'Guiding Bolt': 'Raio Guia',
  'Gust of Wind': 'Rajada de Vento',
  Hallow: 'Consagrar',
  'Hallucinatory Terrain': 'Terreno Alucinatório',
  Harm: 'Ferir',
  Haste: 'Acelerar',
  Heal: 'Curar',
  'Healing Word': 'Palavra de Cura',
  'Heat Metal': 'Aquecer Metal',
  'Hellish Rebuke': 'Repreensão Infernal',
  "Heroes' Feast": 'Banquete dos Heróis',
  Heroism: 'Heroísmo',
  Hex: 'Maldição',
  'Hideous Laughter': 'Riso Medonho',
  'Hold Monster': 'Paralisar Monstro',
  'Hold Person': 'Paralisar Pessoa',
  'Holy Aura': 'Aura Sagrada',
  "Hunter's Mark": 'Marca do Caçador',
  'Hypnotic Pattern': 'Padrão Hipnótico',
  'Ice Knife': 'Faca de Gelo',
  'Ice Storm': 'Tempestade de Gelo',
  Identify: 'Identificar',
  'Illusory Script': 'Escrita Ilusória',
  Imprisonment: 'Aprisionamento',
  'Incendiary Cloud': 'Nuvem Incendiária',
  'Inflict Wounds': 'Infligir Ferimentos',
  'Insect Plague': 'Praga de Insetos',
  'Instant Summons': 'Convocação Instantânea',
  Invisibility: 'Invisibilidade',
  'Irresistible Dance': 'Dança Irresistível',
  Jump: 'Salto',
  Knock: 'Arrombar',
  'Legend Lore': 'Conhecimento Lendário',
  'Lesser Restoration': 'Restauração Menor',
  Levitate: 'Levitar',
  Light: 'Luz',
  'Lightning Bolt': 'Raio',
  'Locate Animals or Plants': 'Localizar Animais ou Plantas',
  'Locate Creature': 'Localizar Criatura',
  'Locate Object': 'Localizar Objeto',
  Longstrider: 'Passada Longa',
  'Mage Armor': 'Armadura de Mago',
  'Mage Hand': 'Mão de Mago',
  'Magic Circle': 'Círculo Mágico',
  'Magic Jar': 'Jarra Mágica',
  'Magic Missile': 'Míssil Mágico',
  'Magic Mouth': 'Boca Mágica',
  'Magic Weapon': 'Arma Mágica',
  'Magnificent Mansion': 'Mansão Magnífica',
  'Major Image': 'Imagem Maior',
  'Mass Cure Wounds': 'Curar Ferimentos em Massa',
  'Mass Heal': 'Cura em Massa',
  'Mass Healing Word': 'Palavra de Cura em Massa',
  'Mass Suggestion': 'Sugestão em Massa',
  Maze: 'Labirinto',
  'Meld into Stone': 'Fundir-se com a Pedra',
  Mending: 'Reparo',
  Message: 'Mensagem',
  'Meteor Swarm': 'Enxame de Meteoros',
  'Mind Blank': 'Mente em Branco',
  'Mind Spike': 'Pico Mental',
  'Minor Illusion': 'Ilusão Menor',
  'Mirage Arcane': 'Miragem Arcana',
  'Mirror Image': 'Imagem Espelhada',
  Mislead: 'Enganar',
  'Misty Step': 'Passo Nevoento',
  'Modify Memory': 'Modificar Memória',
  Moonbeam: 'Raio de Lua',
  'Move Earth': 'Mover Terra',
  Nondetection: 'Não Detecção',
  'Pass without Trace': 'Passar sem Deixar Rastro',
  Passwall: 'Passar pela Parede',
  'Phantasmal Force': 'Força Fantasmagórica',
  'Phantasmal Killer': 'Assassino Fantasmagórico',
  'Phantom Steed': 'Montaria Fantasma',
  'Planar Ally': 'Aliado Planar',
  'Planar Binding': 'Vínculo Planar',
  'Plane Shift': 'Mudança de Plano',
  'Plant Growth': 'Crescimento de Plantas',
  'Poison Spray': 'Borrifo Venenoso',
  Polymorph: 'Metamorfose',
  'Power Word Heal': 'Palavra de Poder: Curar',
  'Power Word Kill': 'Palavra de Poder: Matar',
  'Power Word Stun': 'Palavra de Poder: Atordoar',
  'Prayer of Healing': 'Prece de Cura',
  Prestidigitation: 'Prestidigitação',
  'Prismatic Spray': 'Borrifo Prismático',
  'Prismatic Wall': 'Parede Prismática',
  'Private Sanctum': 'Santuário Privado',
  'Produce Flame': 'Produzir Chama',
  'Programmed Illusion': 'Ilusão Programada',
  'Project Image': 'Projetar Imagem',
  'Protection from Energy': 'Proteção contra Energia',
  'Protection from Evil and Good': 'Proteção contra o Mal e o Bem',
  'Protection from Poison': 'Proteção contra Veneno',
  'Purify Food and Drink': 'Purificar Comida e Bebida',
  'Raise Dead': 'Ressuscitar Morto',
  'Ray of Enfeeblement': 'Raio de Enfraquecimento',
  'Ray of Frost': 'Raio de Gelo',
  'Ray of Sickness': 'Raio de Doença',
  Regenerate: 'Regenerar',
  Reincarnate: 'Reencarnar',
  'Remove Curse': 'Remover Maldição',
  'Resilient Sphere': 'Esfera Resiliente',
  Resistance: 'Resistência',
  Resurrection: 'Ressurreição',
  'Reverse Gravity': 'Inverter Gravidade',
  Revivify: 'Revivificar',
  'Rope Trick': 'Truque da Corda',
  'Sacred Flame': 'Chama Sagrada',
  Sanctuary: 'Santuário',
  'Scorching Ray': 'Raio Abrasador',
  Scrying: 'Vidência',
  'Searing Smite': 'Golpe Abrasador',
  'Secret Chest': 'Baú Secreto',
  'See Invisibility': 'Ver o Invisível',
  Seeming: 'Aparência',
  Sending: 'Envio',
  Sequester: 'Isolar',
  Shapechange: 'Mudar de Forma',
  Shatter: 'Estilhaçar',
  Shield: 'Escudo',
  'Shield of Faith': 'Escudo da Fé',
  Shillelagh: 'Cajado de Batalha',
  'Shining Smite': 'Golpe Brilhante',
  'Shocking Grasp': 'Garra Elétrica',
  Silence: 'Silêncio',
  'Silent Image': 'Imagem Silenciosa',
  Simulacrum: 'Simulacro',
  Sleep: 'Sono',
  'Sleet Storm': 'Tempestade de Granizo',
  Slow: 'Lentidão',
  'Sorcerous Burst': 'Explosão Feiticeira',
  'Spare the Dying': 'Poupar o Moribundo',
  'Speak with Animals': 'Falar com Animais',
  'Speak with Dead': 'Falar com os Mortos',
  'Speak with Plants': 'Falar com Plantas',
  'Spider Climb': 'Escalada de Aranha',
  'Spike Growth': 'Crescimento de Espinhos',
  'Spirit Guardians': 'Guardiões Espirituais',
  'Spiritual Weapon': 'Arma Espiritual',
  'Starry Wisp': 'Fagulha Estelar',
  'Stinking Cloud': 'Nuvem Fétida',
  'Stone Shape': 'Moldar Pedra',
  Stoneskin: 'Pele de Pedra',
  'Storm of Vengeance': 'Tempestade da Vingança',
  Suggestion: 'Sugestão',
  'Summon Dragon': 'Convocar Dragão',
  Sunbeam: 'Raio de Sol',
  Sunburst: 'Explosão Solar',
  Symbol: 'Símbolo',
  Telekinesis: 'Telecinesia',
  'Telepathic Bond': 'Vínculo Telepático',
  Teleport: 'Teleportar',
  'Teleportation Circle': 'Círculo de Teleporte',
  Thaumaturgy: 'Taumaturgia',
  Thunderwave: 'Onda de Trovão',
  'Time Stop': 'Parar o Tempo',
  'Tiny Hut': 'Cabana Minúscula',
  Tongues: 'Línguas',
  'Transport via Plants': 'Transporte via Plantas',
  'Tree Stride': 'Passo da Árvore',
  'True Polymorph': 'Metamorfose Verdadeira',
  'True Resurrection': 'Ressurreição Verdadeira',
  'True Seeing': 'Visão Verdadeira',
  'True Strike': 'Golpe Certeiro',
  Tsunami: 'Tsunami',
  'Unseen Servant': 'Servo Invisível',
  'Vampiric Touch': 'Toque Vampírico',
  'Vicious Mockery': 'Escárnio Cruel',
  'Vitriolic Sphere': 'Esfera Vitriólica',
  'Wall of Fire': 'Parede de Fogo',
  'Wall of Force': 'Parede de Força',
  'Wall of Ice': 'Parede de Gelo',
  'Wall of Stone': 'Parede de Pedra',
  'Wall of Thorns': 'Parede de Espinhos',
  'Warding Bond': 'Vínculo Protetor',
  'Water Breathing': 'Respirar na Água',
  'Water Walk': 'Andar sobre a Água',
  Web: 'Teia',
  Weird: 'Terror Absoluto',
  'Wind Walk': 'Andar no Vento',
  'Wind Wall': 'Parede de Vento',
  Wish: 'Desejo',
  'Word of Recall': 'Palavra de Retorno',
  'Zone of Truth': 'Zona de Verdade',
};

/** Nome do monstro em pt-BR se houver no glossário; senão cai no nome em inglês do SRD. */
export const monsterNamePt = (englishName: string): string =>
  MONSTER_NAMES_PT[englishName] ?? englishName;

/** Nome da magia em pt-BR se houver no glossário; senão cai no nome em inglês do SRD. */
export const spellNamePt = (englishName: string): string =>
  SPELL_NAMES_PT[englishName] ?? englishName;

/** Nomes das magias embutidas que diferem do glossário acima. */
const BUILTIN_ALIASES: Readonly<Record<string, string>> = {
  'Raio de Fogo': 'Fire Bolt',
  'Raio de Gelo': 'Ray of Frost',
  'Toque Chocante': 'Shocking Grasp',
  'Chama Sagrada': 'Sacred Flame',
  'Zombaria Viciosa': 'Vicious Mockery',
  'Mísseis Mágicos': 'Magic Missile',
  'Mãos Flamejantes': 'Burning Hands',
  'Curar Ferimentos': 'Cure Wounds',
  'Palavra Curativa': 'Healing Word',
  'Raio Guia': 'Guiding Bolt',
  'Infligir Ferimentos': 'Inflict Wounds',
  'Imobilizar Pessoa': 'Hold Person',
  Despedaçar: 'Shatter',
  Fúria: 'Rage',
  'Bola de Fogo': 'Fireball',
};

let spellReverse: Map<string, string> | undefined;

/** Inverso de `spellNamePt`: o nome em inglês de uma magia guardada em pt-BR (sem entrada, devolve o próprio). */
export const spellNameEn = (namePt: string): string => {
  spellReverse ??= new Map([
    ...Object.entries(SPELL_NAMES_PT).map(([en, pt]): [string, string] => [pt, en]),
    ...Object.entries(BUILTIN_ALIASES),
  ]);
  return spellReverse.get(namePt) ?? namePt;
};
