import { Spell } from '../../models/spell';

/**
 * Magias do SRD 5.1 que o motor de combate já resolve por completo.
 * (O compêndio de texto completo virá do import do SRD na Fase 6.)
 */
export const SPELLS: Spell[] = [
  {
    id: 'fire-bolt',
    name: 'Raio de Fogo',
    level: 0,
    school: 'Evocação',
    castTime: 'action',
    range: 120,
    target: { kind: 'creature' },
    resolution: { kind: 'attack' },
    damage: { dice: '1d10', type: 'fire', cantrip: true },
    description: 'Ataque de magia à distância. 1d10 de fogo; escala nos níveis 5, 11 e 17.',
  },
  {
    id: 'ray-of-frost',
    name: 'Raio de Gelo',
    level: 0,
    school: 'Evocação',
    castTime: 'action',
    range: 60,
    target: { kind: 'creature' },
    resolution: { kind: 'attack' },
    damage: { dice: '1d8', type: 'cold', cantrip: true },
    description: 'Ataque de magia à distância. 1d8 de gelo.',
  },
  {
    id: 'shocking-grasp',
    name: 'Toque Chocante',
    level: 0,
    school: 'Evocação',
    castTime: 'action',
    range: 5,
    target: { kind: 'creature' },
    resolution: { kind: 'attack' },
    damage: { dice: '1d8', type: 'lightning', cantrip: true },
    description: 'Ataque de magia corpo a corpo. 1d8 elétrico.',
  },
  {
    id: 'sacred-flame',
    name: 'Chama Sagrada',
    level: 0,
    school: 'Evocação',
    castTime: 'action',
    range: 60,
    target: { kind: 'creature' },
    resolution: { kind: 'save', ability: 'dex', onSave: 'none' },
    damage: { dice: '1d8', type: 'radiant', cantrip: true },
    description: 'Salvaguarda de Destreza; 1d8 radiante se falhar.',
  },
  {
    id: 'vicious-mockery',
    name: 'Zombaria Viciosa',
    level: 0,
    school: 'Encantamento',
    castTime: 'action',
    range: 60,
    target: { kind: 'creature' },
    resolution: { kind: 'save', ability: 'wis', onSave: 'none' },
    damage: { dice: '1d4', type: 'psychic', cantrip: true },
    description: 'Salvaguarda de Sabedoria; 1d4 psíquico se falhar.',
  },
  {
    id: 'magic-missile',
    name: 'Mísseis Mágicos',
    level: 1,
    school: 'Evocação',
    castTime: 'action',
    range: 120,
    target: { kind: 'creature' },
    resolution: { kind: 'auto' },
    damage: { dice: '1d4+1', type: 'force', instances: { base: 3, perLevel: 1 } },
    description:
      'Três dardos que sempre acertam (1d4+1 de energia cada); +1 dardo por nível acima do 1º.',
  },
  {
    id: 'burning-hands',
    name: 'Mãos Flamejantes',
    level: 1,
    school: 'Evocação',
    castTime: 'action',
    range: 0,
    target: { kind: 'cone', length: 15 },
    resolution: { kind: 'save', ability: 'dex', onSave: 'half' },
    damage: { dice: '3d6', type: 'fire', perLevel: '1d6' },
    description: 'Cone de 15 ft. Salvaguarda de Destreza; 3d6 de fogo (metade se passar).',
  },
  {
    id: 'cure-wounds',
    name: 'Curar Ferimentos',
    level: 1,
    school: 'Evocação',
    castTime: 'action',
    range: 5,
    target: { kind: 'creature' },
    resolution: { kind: 'auto' },
    heal: { dice: '1d8', perLevel: '1d8', addModifier: true },
    description: 'Toque. Cura 1d8 + modificador de conjuração; +1d8 por nível acima do 1º.',
  },
  {
    id: 'healing-word',
    name: 'Palavra Curativa',
    level: 1,
    school: 'Evocação',
    castTime: 'bonus',
    range: 60,
    target: { kind: 'creature' },
    resolution: { kind: 'auto' },
    heal: { dice: '1d4', perLevel: '1d4', addModifier: true },
    description: 'Ação bônus. Cura 1d4 + modificador de conjuração; +1d4 por nível acima do 1º.',
  },
  {
    id: 'guiding-bolt',
    name: 'Raio Guia',
    level: 1,
    school: 'Evocação',
    castTime: 'action',
    range: 120,
    target: { kind: 'creature' },
    resolution: { kind: 'attack' },
    damage: { dice: '4d6', type: 'radiant', perLevel: '1d6' },
    description: 'Ataque de magia à distância; 4d6 radiante.',
  },
  {
    id: 'inflict-wounds',
    name: 'Infligir Ferimentos',
    level: 1,
    school: 'Necromancia',
    castTime: 'action',
    range: 5,
    target: { kind: 'creature' },
    resolution: { kind: 'attack' },
    damage: { dice: '3d10', type: 'necrotic', perLevel: '1d10' },
    description: 'Ataque de magia corpo a corpo; 3d10 necrótico.',
  },
  {
    id: 'hold-person',
    name: 'Imobilizar Pessoa',
    level: 2,
    school: 'Encantamento',
    castTime: 'action',
    range: 60,
    target: { kind: 'creature' },
    resolution: { kind: 'save', ability: 'wis', onSave: 'none' },
    condition: { name: 'paralyzed', rounds: 10 },
    concentration: true,
    description:
      'Salvaguarda de Sabedoria; se falhar, fica paralisado (concentração, até 1 minuto).',
  },
  {
    id: 'shatter',
    name: 'Despedaçar',
    level: 2,
    school: 'Evocação',
    castTime: 'action',
    range: 60,
    target: { kind: 'sphere', radius: 10 },
    resolution: { kind: 'save', ability: 'con', onSave: 'half' },
    damage: { dice: '3d8', type: 'thunder', perLevel: '1d8' },
    description: 'Esfera de 10 ft. Salvaguarda de Constituição; 3d8 trovejante (metade se passar).',
  },
  {
    id: 'fireball',
    name: 'Bola de Fogo',
    level: 3,
    school: 'Evocação',
    castTime: 'action',
    range: 150,
    target: { kind: 'sphere', radius: 20 },
    resolution: { kind: 'save', ability: 'dex', onSave: 'half' },
    damage: { dice: '8d6', type: 'fire', perLevel: '1d6' },
    description: 'Esfera de 20 ft. Salvaguarda de Destreza; 8d6 de fogo (metade se passar).',
  },
];

const BY_ID = new Map(SPELLS.map((s) => [s.id, s]));

export const getSpell = (id: string): Spell | undefined => BY_ID.get(id);
